// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDIQocN-qvKNPVG_DMwQ0PdocMO1yK7s',
    appId: '1:960292503618:web:94ddba749df8ba9066addb',
    messagingSenderId: '960292503618',
    projectId: 'moneywise-3af52',
    authDomain: 'moneywise-3af52.firebaseapp.com',
    storageBucket: 'moneywise-3af52.firebasestorage.app',
    measurementId: 'G-KXDQC6D7CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7CnvOL7qqxQ748VNMVNFGn6ASKWvjFk',
    appId: '1:960292503618:android:88db9f3dd65e4e8a66addb',
    messagingSenderId: '960292503618',
    projectId: 'moneywise-3af52',
    storageBucket: 'moneywise-3af52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHKKYFHE5yZZZl1vfo-xl1hWOlorzTn1Q',
    appId: '1:960292503618:ios:140995dcb1018aa266addb',
    messagingSenderId: '960292503618',
    projectId: 'moneywise-3af52',
    storageBucket: 'moneywise-3af52.firebasestorage.app',
    iosClientId: '960292503618-8ahn2gmnh2iail7mkcca7ij68a14d3q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHKKYFHE5yZZZl1vfo-xl1hWOlorzTn1Q',
    appId: '1:960292503618:ios:140995dcb1018aa266addb',
    messagingSenderId: '960292503618',
    projectId: 'moneywise-3af52',
    storageBucket: 'moneywise-3af52.firebasestorage.app',
    iosClientId: '960292503618-8ahn2gmnh2iail7mkcca7ij68a14d3q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRDIQocN-qvKNPVG_DMwQ0PdocMO1yK7s',
    appId: '1:960292503618:web:90d07ac43402a10e66addb',
    messagingSenderId: '960292503618',
    projectId: 'moneywise-3af52',
    authDomain: 'moneywise-3af52.firebaseapp.com',
    storageBucket: 'moneywise-3af52.firebasestorage.app',
    measurementId: 'G-XMSCEQ6B9J',
  );
}
